### PR TITLE
More prints, better error handling.

### PR DESCRIPTION
**Pull request by joaofayad**
After some feedback from people having trouble running the code, I added a few things to help diagnose the problem.

### CODE REVIEW

**Comment by DennisEckmeier** [comment]
careylab/LocoMouse is the version for the paper. As I understood it, this version should not be changed?

Would you maybe want to make the changes in the careylab/LocoMouse_Dev version, instead?

**Comment by joaofayad** [comment]
This is not functionality, is just some prints to make diagnosing why the
code doesn't run easier. I got feedback from someone trying to use it and
they couldn't make it run. I can't help them without some output of the
code. Given that this is the link everyone will go to, I imagined it would
be the place to make such changes.

On 26 November 2015 at 18:41, Dennis Eckmeier notifications@github.com
wrote:

> careylab/LocoMouse is the version for the paper. As I understood it, this
> version should not be changed?
> 
> Would you maybe want to make the changes in the careylab/LocoMouse_Dev
> version, instead?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/careylab/LocoMouse/pull/2#issuecomment-159859579.

## 

João Fayad

**Comment by DennisEckmeier** [comment]
I made a copy of the original code, and will merge this pull request, since it didn't change the functionality. You could also suggest to them to use the Dev version?

**Comment by joaofayad** [comment]
I think the readme for paper version should state something about the Dev
version. Just a small sentence saying something on the lines of "this is
the core tracker for the paper. For improvements and extra functionality
(GUI, Training models, etc) please check the Dev repository".

I don't think there is a need to keep the repository exactly as it was when
the paper was accepted. But any changes I make are only to make it easier
to run as is. For anything else people should go to the dev version for
sure..

On 26 November 2015 at 19:04, Dennis Eckmeier notifications@github.com
wrote:

> Merged #2 https://github.com/careylab/LocoMouse/pull/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/careylab/LocoMouse/pull/2#event-475415874.

## 

João Fayad

**Comment by DennisEckmeier** [comment]
Sounds reasonable :)

**Pull request merged**
